### PR TITLE
pkg/sync: return error when fail to start snapshot purge on one of the replicas

### PR DESCRIPTION
**Pull request by PhanLe1010**
There are 2 callers of the SnapshotPurge command:
1. From Longhorn manager API
2. After finish rebuilding a new replica and `Automatically Cleanup System Generated Snapshot` setting is on

This PR make sure that the error when start SnapshotPurge is reported back to Longhorn manager. It makes debugging easier.

longhorn/longhorn#1895

### CODE REVIEW

**Review by joshimoo — COMMENTED** [review]
In principle LGTM, we would fail if we fail to create the replica client in line 152.
What are the failure cases for that and are we expected to mark the replica as failure as a result for an intermittent connection failure? cc @shuo-wu 

https://github.com/longhorn/longhorn-engine/pull/556/files#diff-2e7c810166140fd7a58d6bdb610fef7e6de8f5f9ad2002659392878ecafd6befR152

**Review by shuo-wu — CHANGES_REQUESTED** [review]
Can we group all replica errors here rather than returning an error immediately when the 1st error is found? e.g., https://github.com/longhorn/longhorn-engine/blob/b9e072eb19cfcc27894e10a8e60794c66ca918f8/pkg/sync/backup.go#L164

**Comment by shuo-wu** [comment]
> In principle LGTM, we would fail if we fail to create the replica client in line 152.
> What are the failure cases for that and are we expected to mark the replica as failure as a result for an intermittent connection failure? cc @shuo-wu
> 
> https://github.com/longhorn/longhorn-engine/pull/556/files#diff-2e7c810166140fd7a58d6bdb610fef7e6de8f5f9ad2002659392878ecafd6befR152

Yes. IIRC, the engine process will mark the replica as mode `ERROR` if the connection is lost for a while.

**Comment by shuo-wu** [comment]
BTW, there is one more caller of the purge command: the restore function https://github.com/longhorn/longhorn-engine/blob/b9e072eb19cfcc27894e10a8e60794c66ca918f8/pkg/sync/backup.go#L208

**Comment by PhanLe1010** [comment]
Thanks @joshimoo and @shuo-wu . I grouped the errors together.

**Review by shuo-wu — APPROVED** [review]

**Pull request merged**
