### PR TITLE
Update backupstore to v0.0.0-20200709195833-7392333d6d22

### PR DESCRIPTION
**Pull request by boknowswiki**
Update backupstore to v0.0.0-20200709195833-7392333d6d22 for fixing the
LastBackup fields in volume.cfg when deleting the latest backup

https://github.com/longhorn/longhorn/issues/1381

Signed-off-by: Bo Tao <bo.tao@rancher.com>

### CODE REVIEW

**Comment by yasker** [comment]
test_backup.py failed. Check the drone log for details.

**Comment by yasker** [comment]
I've retriggered the test. The failed result is at https://drone-pr.rancher.io/longhorn/longhorn-engine/681

**Comment by joshimoo** [comment]
@boknowswiki @yasker The test failure happens, because it's expecting a full backup creation since we removed the prior backup(2).
But now that we set the lastBackup variables after the delete operation to the next closest snapshot, we would be doing an incremental backup.

**Comment by boknowswiki** [comment]
> @boknowswiki @yasker The test failure happens, because it's expecting a full backup creation since we removed the prior backup(2).
> But now that we set the lastBackup variables after the delete operation to the next closest snapshot, we would be doing an incremental backup.
> 
> It would be okay to change the assert to expect an incremental backup.
> Or to stick with the prior expectation, delete all prior backups (0,1,2)

@yasker and @joshimoo , based on my understand, the incremental will be set if the lastbackup is not nil. So in this case, it should be true. And I think the fix should be change `assert backup3['IsIncremental'] is False` to `assert backup3['IsIncremental'] is True`. Please let me know my understand is not correct.

Thanks,
Bo

**Comment by joshimoo** [comment]
> Please let me know my understand is not correct.

Your understanding is correct and updating the test to be incremental is an appropriate solution.

**Comment by yasker** [comment]
Do we still have test to cover the full backup case? Backup a same snapshot twice should trigger full backup as well.

**Comment by boknowswiki** [comment]
> Do we still have test to cover the full backup case? Backup a same snapshot twice should trigger full backup as well.

I think so, there is `# final full backup after unavailable backup` on line 263

**Pull request merged**
