### PR TITLE
[BACKPORT][v1.3.x] vendor: update sparse-tools (backport #824) 

### PR DESCRIPTION
**Pull request by derekbit**
Longhorn/longhorn#5130

### CODE REVIEW

**Comment by innobead** [comment]
PR check failed?

**Comment by derekbit** [comment]
> PR check failed?

Just noticed the some apis' parameters are changed. Sould we backport to v1.3.x?

**Comment by innobead** [comment]
> > PR check failed?
> 
> Just noticed the some apis' parameters are changed. Sould we backport to v1.3.x?

You are right, it's about the new checksum introduction as below. 

Unfortunately, Golang does not have function overloading or function default parameters to cause this incompatible change. The only solution seems just to branch the sparse_tools library or next time, we should create a new method instead of changing the existing method, but this way is really old school like C and it will need the caller to do change accordingly.  

```
# github.com/longhorn/longhorn-engine/pkg/sync/rpc
pkg/sync/rpc/server.go:343:27: not enough arguments in call to sparse.SyncFile
	have (string, string, number, bool)
	want (string, string, int, bool, bool)
pkg/sync/rpc/server.go:374:30: not enough arguments in call to sparse.SyncContent
	have (string, *replica.Replica, int64, string, number, bool)
	want (string, sparse.ReaderWriterAt, int64, string, int, bool, bool)
```

**Comment by derekbit** [comment]
> Unfortunately, Golang does not have function overloading or function default parameters to cause this incompatible change. The only solution seems just to branch the sparse_tools library or next time, we should create a new method instead of changing the existing method, but this way is really old school like C and it will need the caller to do change accordingly.

One idea is to make lib's api parameters like
```
func mount(souurce, mountpoint string, mountOptions MountOptions)

type MountOptions struct {
   vers string
   ro bool
   ...
}
```

`souurce` and `mountpoint` are always necessary.
The fields in `MountOptions` are optional for different versions.

**Comment by innobead** [comment]
yeah, this is what I thought as well. 

Should better design the library to make it backward compatible enough, but based on Golang's capability, A new method or object/structure parameter is the way to adopt.

**Pull request closed without merging**
