### PR TITLE
fix(logging): demote some Info logging to Debug

### PR DESCRIPTION
**Pull request by james-munson**
#### Which issue(s) this PR fixes:

Part of https://github.com/longhorn/longhorn/issues/6702

#### What this PR does / why we need it:

Demote some noisy Info-level logging to Debug.  Routine snapshotting can flood logs with Info-level output.

### CODE REVIEW

**Review by PhanLe1010 — APPROVED** [review]
LGTM

Same comment as https://github.com/longhorn/longhorn-instance-manager/pull/700#pullrequestreview-2402786862

**Comment by derekbit** [comment]
These log messages only print once for each operation and won't result in flooding the logs, so I think we should keep them at the INFO level.

**Comment by derekbit** [comment]
> These log messages only print once for each operation and won't result in flooding the logs, so I think we should keep them at the INFO level.

WDYT? @PhanLe1010 @innobead @james-munson

**Comment by james-munson** [comment]
As noted in the related https://github.com/longhorn/longhorn-instance-manager/pull/700, these logs were picked because they repeated more than 1000 times each over a two-week period in a recent escalation support bundle.  Granted, that was in an environment doing a good amount of snapshots.

**Comment by derekbit** [comment]
> As noted in the related https://github.com/longhorn/longhorn-instance-manager/pull/700, these logs were picked because they repeated more than 1000 times each over a two-week period in a recent escalation support bundle. Granted, that was in an environment doing a good amount of snapshots.

I think it is not a good reason to demote the log level of this one-time and important log messages.

Do you know which pod log is the user complaining about? I remember longhorn-manager pods rather than longhorn-instance-manager pods?

**Comment by james-munson** [comment]
> Do you know which pod log is the user complaining about? I remember longhorn-manager pods rather than longhorn-instance-manager pods?

There were 138 MB of longhorn-manager logs over 4 nodes, and 108 MB of instance-manager logs, so 246 MB in total.  The breakdown is in https://github.com/longhorn/longhorn/issues/6702#issuecomment-2436512562

If the consensus is that these are too likely to be needed, I will close this PR as well, and focus on propagating the global log level setting.

**Pull request closed without merging**
