### PR TITLE
vendor: update backupstore

### PR DESCRIPTION
**Pull request by mantissahz**
#### Which issue(s) this PR fixes:

Issue longhorn/longhorn#2810, longhorn/longhorn#7098

#### What this PR does / why we need it:

BACKPORT: Relax S3 client retry intervals, for throttled requests

#### Additional documentation or context
Regression test: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6188/

### CODE REVIEW

**Comment by innobead** [comment]
@mantissahz any reasons we backported @derekbit commits as well?

**Comment by mantissahz** [comment]
>@mantissahz any reasons we backported @derekbit commits as well? are they related to your backport

Because updating the vendor `backupstore` to `S3 client retry intervals, for throttled requests` will also include the commits [fa25b1a97f](https://github.com/longhorn/backupstore/commit/fa25b1a97ffdd1d009920afeed3f28191c666d36), [3495f73689](https://github.com/longhorn/backupstore/commit/3495f73689dc3a9073658c8ec931edfa9b07d333), and 
[e9de675eed](https://github.com/longhorn/backupstore/commit/e9de675eed473dd1dfc9f7ba0eb33ea09d0bfe22), I need to pick those two commits of @derekbit.

No, they are not related to `S3 client retry intervals, for throttled requests`.

**Comment by innobead** [comment]
See if @derekbit has any concerns by review.

**Comment by derekbit** [comment]
> See if @derekbit has any concerns by review.

I'm fine with the backport. The two commits are only refactoring the framework.

**Review by innobead — APPROVED** [review]

**Pull request merged**
