### PR TITLE
Add integration test for incremental backup logic

### PR DESCRIPTION
**Pull request by joshimoo**
We had some issues with incremental / full backups, this test covers
cases where we create a duplicate volume for a prior existing volume

longhorn/longhorn#1294
longhorn/backupstore#34

Signed-off-by: Joshua Moody <joshua.moody@rancher.com>

### CODE REVIEW

**Comment by joshimoo** [comment]
will add the go mod update once longhorn/backupstore#34 is merged

**Comment by yasker** [comment]
Add the backup store change before the integration test, so the integration test won't fail during `git bisect`

**Comment by joshimoo** [comment]
> Add the backup store change before the integration test, so the integration test won't fail during `git bisect`

I already did, unless I screwed it up?

**Comment by joshimoo** [comment]
Yep looks good on my end.

**Comment by yasker** [comment]
Yeah it looks good when I checked it out locally. Seems it's that GitHub bug again:

Screen Shot 2020-05-07 at 8 53 45 PM

**Pull request merged**
