### PR TITLE
 Rebuilding speedup:  fast sync by checking disk files change timestamps and checksums

### PR DESCRIPTION
**Pull request by derekbit**
[Longhorn 4783](https://github.com/longhorn/longhorn/issues/4783)

Signed-off-by: Derek Su <derek.su@suse.com>

### CODE REVIEW

**Comment by derekbit** [comment]
Runing e2e. Will rebase later.

**Comment by derekbit** [comment]
Runing e2e. Will rebase later.

**Review by innobead — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
Merge this until the dep gets updated.

**Review by innobead — APPROVED** [review]

**Pull request merged**
