### PR TITLE
Update go-iscsi-helper and backupstore in vendor

### PR DESCRIPTION
**Pull request by andrewd-zededa**
Also handle sys version conflict and compile error
with snapBlockSize->backupBlockSize in pkg/replica/backup.go

Two commits by @derekbit were cherry-picked over to fix compilation errors as well.

The motivation for this PR is to incorporate the original 'containerd-shim' process namespace fix in go-iscsi-helper into the longhorn-engine 1.5.x build and in the pending 1.5.4 release.  The full discussion for that fix is contained in https://github.com/longhorn/longhorn/issues/5693 

Please let me know if I'm following the correct process here, thanks!

### CODE REVIEW

**Comment by innobead** [comment]
@andrewd-zededa Don't we need to introduce this to the master, then backport to 1.5/1.4?

**Comment by andrewd-zededa** [comment]
@innobead master and v1.6.0-dev already works in this case and has moved to a different method of looking up the namespace directory where iscsid is searched for (https://github.com/longhorn/longhorn-engine/blob/master/vendor/github.com/longhorn/go-iscsi-helper/util/process.go) instead of docker/containerd/containerd-shim.  I tried backporting that first and if I remember correctly it began to pull in more changes so I switched to this instead which was quicker.  It looks like this original fix was just never fully incorporated into the build.

Would you like me to instead revisit backporting the new iscsid method instead?

**Comment by andrewd-zededa** [comment]
Just bumping this to keep it open, I'm working on it now

**Comment by innobead** [comment]
@andrewd-zededa sorry for the late review. Can you help rebase this PR due to conflicts first? Thanks.

**Comment by andrewd-zededa** [comment]
@innobead yes I'll rebase

**Comment by ChanYiLin** [comment]
Hi @andrewd-zededa 
Sorry for the late reply, I am here to help you proceed the progress.

So for backporting the update in `go-iscsi-helper` to upcoming v1.5.4 or v1.5.x
What you have to do is
1. fork the repo  `longhorn/longhorn-engine`
2. check out upstream `v1.5.x`
    - this is the head of v1.5.x, we will cut release from this branch every time we are releasing v1.5.x, for example,  upcoming v1.5.4 
3. create your branch from `v1.5.x`
4. update the vendor of `go-iscsi-helper`
    - `go get github.com/longhorn/go-iscsi-helper@${LATEST_COMMIT_OF_MASTER}` (go-iscsi-helper is common for all longhorn version)
    - `go mod tidy`
    - `go mod vendor`
5. Create a PR to merge your branch to upstream `v1.5.x`

This the flow of how we update the vendor in previous version for the patch version
That is, in this PR, if you have to fix the conflicts or modify some `/pkg/...` code, that means something wrong.
Can you help me to close this PR and follow the above steps to recreate the PR again?
Thanks!

**Comment by andrewd-zededa** [comment]
Ok, sounds like I need to drop my existing commits and redo, I'll try to get that completed this afternoon

**Comment by andrewd-zededa** [comment]
@ChanYiLin I haven't pushed it up yet, but I just created a fresh branch created based off v1.5.x, did a go get of the latest master commit of go-iscsi-helper and it pulls in a number of go.mod updates, in addition to hitting a build issue which I have not yet looked into.  I'll try the slightly older release in my original pr next.


```
diff --git a/go.mod b/go.mod
index b7299e27..d60674af 100644
--- a/go.mod
+++ b/go.mod
@@ -6,21 +6,21 @@ require (
 	github.com/docker/go-units v0.3.3
 	github.com/gofrs/flock v0.8.1
 	github.com/golang/protobuf v1.5.3
-	github.com/google/uuid v1.3.0
+	github.com/google/uuid v1.3.1
 	github.com/gorilla/handlers v1.5.1
 	github.com/gorilla/mux v1.8.0
 	github.com/longhorn/backupstore v0.0.0-20231025000449-5316e8b5320d
-	github.com/longhorn/go-iscsi-helper v0.0.0-20230802055236-4ec8edae3fad
+	github.com/longhorn/go-iscsi-helper v0.0.0-20240104130856-4bd63e2b676a
 	github.com/longhorn/sparse-tools v0.0.0-20230408015858-c849def39d3c
 	github.com/moby/moby v23.0.2+incompatible
 	github.com/pkg/errors v0.9.1
 	github.com/rancher/go-fibmap v0.0.0-20160418233256-5fc9f8c1ed47
 	github.com/rancher/go-rancher v0.1.1-0.20190307222549-9756097e5e4c
-	github.com/sirupsen/logrus v1.9.0
+	github.com/sirupsen/logrus v1.9.3
 	github.com/urfave/cli v1.22.5
-	golang.org/x/net v0.8.0
-	golang.org/x/sys v0.7.0
-	google.golang.org/grpc v1.53.0
+	golang.org/x/net v0.16.0
+	golang.org/x/sys v0.13.0
+	google.golang.org/grpc v1.60.1
 	gopkg.in/check.v1 v1.0.0-20201130134442-10cb98267c6c
 	gopkg.in/cheggaaa/pb.v2 v2.0.0-20190301131520-f907f6f5dd81
 )
@@ -31,7 +31,7 @@ require (
 	github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v0.3.0 // indirect
 	github.com/aws/aws-sdk-go v1.34.2 // indirect
 	github.com/beorn7/perks v1.0.1 // indirect
-	github.com/c9s/goprocinfo v0.0.0-20190309065803-0b2ad9ac246b // indirect
+	github.com/c9s/goprocinfo v0.0.0-20210130143923-c95fcf8c64a8 // indirect
 	github.com/cespare/xxhash/v2 v2.2.0 // indirect
 	github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d // indirect
 	github.com/fatih/color v1.7.0 // indirect
@@ -39,29 +39,34 @@ require (
 	github.com/gammazero/deque v0.2.1 // indirect
 	github.com/gammazero/workerpool v1.1.3 // indirect
 	github.com/go-logr/logr v1.2.4 // indirect
+	github.com/go-ole/go-ole v1.2.6 // indirect
 	github.com/gorilla/context v1.1.1 // indirect
 	github.com/gorilla/websocket v1.4.2 // indirect
 	github.com/jmespath/go-jmespath v0.3.0 // indirect
 	github.com/kr/pretty v0.3.1 // indirect
 	github.com/kr/text v0.2.0 // indirect
-	github.com/longhorn/nsfilelock v0.0.0-20200723175406-fa7c83ad0003 // indirect
+	github.com/longhorn/go-common-libs v0.0.0-20240103081802-3993c5908447 // indirect
 	github.com/mattn/go-colorable v0.1.4 // indirect
 	github.com/mattn/go-runewidth v0.0.5-0.20181218000649-703b5e6b11ae // indirect
 	github.com/matttproud/golang_protobuf_extensions v1.0.4 // indirect
+	github.com/mitchellh/go-ps v1.0.0 // indirect
 	github.com/moby/sys/mountinfo v0.6.2 // indirect
 	github.com/pierrec/lz4/v4 v4.1.17 // indirect
+	github.com/power-devops/perfstat v0.0.0-20210106213030-5aafc221ea8c // indirect
 	github.com/prometheus/client_golang v1.15.0 // indirect
 	github.com/prometheus/client_model v0.3.0 // indirect
 	github.com/prometheus/common v0.42.0 // indirect
 	github.com/prometheus/procfs v0.9.0 // indirect
 	github.com/rogpeppe/go-internal v1.9.0 // indirect
 	github.com/russross/blackfriday/v2 v2.0.1 // indirect
+	github.com/shirou/gopsutil/v3 v3.23.7 // indirect
 	github.com/shurcooL/sanitized_anchor_name v1.0.0 // indirect
 	github.com/slok/goresilience v0.2.0 // indirect
+	github.com/yusufpapurcu/wmi v1.2.3 // indirect
 	go.uber.org/multierr v1.11.0 // indirect
 	golang.org/x/text v0.13.0 // indirect
-	google.golang.org/genproto v0.0.0-20230110181048-76db0878b65f // indirect
-	google.golang.org/protobuf v1.30.0 // indirect
+	google.golang.org/genproto/googleapis/rpc v0.0.0-20231002182017-d307bd883b97 // indirect
+	google.golang.org/protobuf v1.31.0 // indirect
 	gopkg.in/cheggaaa/pb.v1 v1.0.28 // indirect
 	gotest.tools/v3 v3.4.0 // indirect
 	k8s.io/apimachinery v0.27.1 // indirect
```

```
.../binarylog/grpc_binarylog_v1/binarylog.pb.go | 4 +- .../grpc/health/grpc_health_v1/health.pb.go | 4 +- .../grpc/health/grpc_health_v1/health_grpc.pb.go | 37 +- .../grpc_reflection_v1alpha/reflection.pb.go | 87 +- .../grpc_reflection_v1alpha/reflection_grpc.pb.go | 10 +- .../protobuf/types/descriptorpb/descriptor.pb.go | 1011 ++++--- .../protobuf/types/known/anypb/any.pb.go | 70 +- .../types/known/timestamppb/timestamp.pb.go | 2 +-
GRPC generated code is not up to date
FATA[0051] exit status 1                                
make: *** [Makefile:11: ci] Error 1
```

**Comment by ChanYiLin** [comment]
@andrewd-zededa  I think there are too many changes in go-common-lib/go-iscsi-helper these two packages
And some of the changes we didn't modify longhorn-engine v1.5.x to fit the changes
Might need some time to take a look.

For these kind of common lib, when we did some changes
We might need to backport it in related repos as well, otherwise, when we want to update the library in this older version, we will need to solve many unrelated updates.
cc @innobead @c3y1huang @derekbit

**Comment by ChanYiLin** [comment]
Hi @andrewd-zededa 
I will take care of the backport from here, the issue might become too tricky

Here is the context.
longhorn-engine depends on `go-iscsi-helper`.
We move some `go-iscsi-helper` functions to `go-common-lib` later on in v1.6.x, however, we didn't update the changes in longhorn-engine v1.5.x
That is, the `go-iscsi-helper` is too old in longhorn-engine v1.5.x, and when we update it to the latest version, we have to manually update some code base to meet the changes of  `go-iscsi-helper/go-common-lib`

cc @longhorn/dev

**Pull request closed without merging**
