### PR TITLE
Remove ping timeout

### PR DESCRIPTION
**Pull request by keithalucas**
The ping timeout was occurring in scenarios with limited bandwidth and
high network usage.  The limited bandwidth and high network traffic was
delaying the transmission of the ping message and the response, causing
the timeout to occur when the replica was in fact operational.

Without the ping timeout, the code can still take advantage of the
default TCP keep alive timeout that golang's networking code sets to 15
seconds.  The TCP keep alive timeout is a socket option whose
functionality is implemented by the Linux kernel.

https://github.com/longhorn/longhorn/issues/2882

Signed-off-by: Keith Lucas <keith.lucas@suse.com>

### CODE REVIEW

**Review by yasker — CHANGES_REQUESTED** [review]
1. We need an issue associate with the PR.
2. Do we need to remove `ping` from the protocol as well? 

Also, somehow CI failed.

**Comment by keithalucas** [comment]
> 1. We need an issue associate with the PR.
> 2. Do we need to remove `ping` from the protocol as well?
> 
> Also, somehow CI failed.

I associated the PR with github.com/longhorn/longhorn/issue/2882.  I felt like I should have removed ping from the protocol  because it would be confusing if it's there and not used so I removed it.  https://github.com/longhorn/sparse-tools/blob/a0fb4226a960dfa0a77a843b052a44824a9d729a/stats/stats.go#L87 sparse-tools still references ping which could do in another pull request.  I believe those python tests indirectly rely on a ping timeout occurring.  I need to investigate and fix them.

**Comment by yasker** [comment]
Yes, let's address the sparse file in another PR. That one seems hardcoded in its own repo so I guess there is no dependency.

**Review by yasker — DISMISSED** [review]
LGTM. Pending the CI result.

**Comment by keithalucas** [comment]
Upon investigation, in the tests that fail, the ping is necessary because the controller uses it to get the status of the replica when the replica is closed or failed.  I added the ping back but the ping doesn't timeout.  This allows the controller to see that a replica has been closed and set the replica's mode to ERR.  In the future, it might make more sense to have the replica disconnect when it is closed or send a message indicating a change in status.

**Comment by yasker** [comment]
CI was still failing on ARM part, I just restarted it.

**Comment by innobead** [comment]
Failed again restarted to see the result

**Review by innobead — APPROVED** [review]

**Pull request merged**
