### PR TITLE
Speed up backup creation: Avoid using channel in CompareSnapshot

### PR DESCRIPTION
**Pull request by shuo-wu**
longhorn/longhorn#2218

### CODE REVIEW

**Review by jenting — APPROVED** [review]
Not sure had you test the max file size could be finished within 3 mins or not.
For example 16TB.

**Comment by shuo-wu** [comment]
> Not sure had you test the max file size could be finished within 3 mins or not.
> For example 16TB.

This is not the ultimate solution for the timeout issue. But removing channel would speed up the process.

**Review by joshimoo — APPROVED** [review]
Discussed with @shuo-wu this is sort of a hack to get it into v1.1.2
For v1.2 we can parallesize the creation of the sectors -> file map.

map: Either by utilising a bitsets for each file
reduce: Then merging them into the final sector->file map.

map: Or by having each go routine create & write on a buffered output channel of the form:
Location{
sector uint64
fileID byte
}

reduce: Then merging the channels unified output channel which can then be processed by the main routine for writing to the sector -> file map since a higher fileID overwrites a lower fileID for a sector, this process will lead to the correct sector -> fileID map.

**Comment by joshimoo** [comment]
Leaving a note about the memory consumption for the bit set approach.
```
sectorsPerGB = (1024×1024×1024)÷(4×1024) = 262144
bytesPerGB = sectorsPerGB / 8 = 32768 bytes = 32KB

So for each GB of filesize we only need to store 32KB in the bitset.
100 GB = 32 * 100 = 3.125MB
1TB = 31.25MB

```

So the memory consumption is quite small for the bitset approach.

**Pull request merged**
