### PR TITLE
Backupstore file locks

### PR DESCRIPTION
**Pull request by joshimoo**
longhorn/longhorn#612

### CODE REVIEW

**Comment by joshimoo** [comment]
Punted for 1.0.2

**Comment by joshimoo** [comment]
The build failure is caused by an error in the new restore logic?
https://github.com/longhorn/longhorn-engine/blob/4f6eefe90709a219e8d61eaccca263048a3fdd4c/pkg/sync/rpc/server.go#L199

Since we fail the restore operation on purpose to test the delete lock even though the actual restore operation wasn't even started yet, this will still be classified as errorState and not recovered. So after removing the Delete lock the following restore operation should succeed but because the previous restore operation failed (wasn't even started) the code no longer allows for restores?

@shuo-wu Shouldn't this just fallback to full restores?

**Comment by shuo-wu** [comment]
> The build failure is caused by an error in the new restore logic?
> https://github.com/longhorn/longhorn-engine/blob/4f6eefe90709a219e8d61eaccca263048a3fdd4c/pkg/sync/rpc/server.go#L199
> 
> Since we fail the restore operation on purpose to test the delete lock even though the actual restore operation wasn't even started yet, this will still be classified as errorState and not recovered. So after removing the Delete lock the following restore operation should succeed but because the previous restore operation failed (wasn't even started) the code no longer allows for restores?
> 
> @shuo-wu Shouldn't this just fallback to full restores?

All errors after the restore initialization will be blindly recorded in `RestoreStatus`. Some errors won't affect the following restores and some are critical. But it would be complicated to enable Longhorn to distinguish the errors and start a full restore as the fallback. Instead, Longhorn can directly mark the replica as ERROR first then see if the existing data can be reused during the following rebuilding. (The data reusing is not implemented yet.)

As for the failure you encounter in the test, can you check if [function `sync_agent_server_reset `](https://github.com/longhorn/longhorn-engine/blob/4f6eefe90709a219e8d61eaccca263048a3fdd4c/integration/common/cmd.py#L167) works for you? :
https://github.com/longhorn/longhorn-engine/blob/4f6eefe90709a219e8d61eaccca263048a3fdd4c/pkg/sync/rpc/server.go#L257
Or you can create a separate test for each restore related case.

**Comment by joshimoo** [comment]
longhorn/longhorn-engine#529 fixed the valid test failure
there is still a flaky test tracked at longhorn/longhorn#1628

**Comment by joshimoo** [comment]
This is good to go, I kicked of the build again and we can look into the root cause of the flaky test during the bug fixing phase.

**Pull request merged**
