### PR TITLE
Add support for arm64 (draft)

### PR DESCRIPTION
**Pull request by ivang**
Addresses partially longhorn/longhorn#6 by adding support for arm64 (armhf not supported).

Possibly due to some race conditions integration tests were initially failing, which was resolved by introducing sleep at the problematic places. This is clearly a workaround and a cleaner solution would be needed.

With some small changes in longhorn-manager and longhorn-ui, I was able to deploy longhorn on k3s cluster of 4 Raspberry Pi 4s and, as far as I can tell, it seems to be functioning properly.

PRs for [longhorn-manager](https://github.com/longhorn/longhorn-manager/pull/626) and [longhorn-ui](https://github.com/longhorn/longhorn-ui/pull/303) are part of this.

Same as https://github.com/longhorn/longhorn-engine/pull/513 but all commits are signed off.

### CODE REVIEW

**Comment by yasker** [comment]
Thanks for your PR @ivang ! Please give us a few days to review it since we're in the release cycle of v1.0.1 right now.

Also, I am wondering what kind of test you've done so far? We might want to enable drone (our CI system) for ARM64 as well.

**Comment by ivang** [comment]
Thank you @yasker, there's really no rush on my part at all.

As for the tests, I simply ran the build pipeline locally, on a [64bit Raspberry Pi OS](https://www.raspberrypi.org/forums/viewtopic.php?f=117&t=275370), by typing `make`, as part of which `scripts/integration-tests` was executed. That's all, I didn't do anything special but, as I mentioned, I had to work around some race conditions by introducing `time.sleep()` in several places within the tests themselves. Those sleeps are mostly introduced between the creation of a ReplicaClient object and the first operation executed on it. This calls for a cleaner solution, of course, but I didn't know any better.

With the tests passing, and similar modifications made to longhorn-manager and longhorn-ui, I was able to deploy the longhorn system on my k3s cluster of 64bit-enabled Raspberry Pi 4s. I was also able to claim longhorn PVs and it seems to be working fine so far. That's about as much manual testing I've done so far.

It would be interesting to see if this works on environments other than mine, so I'd be curious to see the output of an ARM64-enabled drone.

**Comment by agustinvinao** [comment]
Hi, Any update on this? it will be a good step for the project to being able to run this on ARM . thanks

**Comment by yasker** [comment]
@agustinvinao We will start to review this PR soon. Currently trying to get some ARM resources for build/testing purposes.

**Comment by lexfrei** [comment]
@yasker any news? I can give you a ssh access to my pi(s) if you need this kind of arm resources :)
Just pm me in telegram

**Comment by yasker** [comment]
Thanks for the offering @lexfrei ! We finally got some ARM machines last week and starts working on this PR.

We're planning to include the ARM support in the upcoming Longhorn v1.1.0 release as an experimental feature.

**Review by boknowswiki — CHANGES_REQUESTED** [review]
https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-${ARCH} /tini

**Comment by agustinvinao** [comment]
Hey, sorry to insist on this.

Can we help on any way to make this available? 
it feels like after a month we dont have any news about it. Do you have any estimation when v1.1 may be available with this? 

Please let us know how to help.

**Comment by yasker** [comment]
@agustinvinao Everything is almost ready, Longhorn team has taken over the work. If you want to give it an early try, you should able to [deploy from github.com/longhorn/longhorn-manager `master` branch (which is the development branch)](https://github.com/longhorn/longhorn-manager#deployment) on an ARM64 platform.

Let us know if you can successfully do it.

**Comment by agustinvinao** [comment]
> @agustinvinao Everything is almost ready, Longhorn team has taken over the work. If you want to give it an early try, you should able to [deploy from github.com/longhorn/longhorn-manager `master` branch (which is the development branch)](https://github.com/longhorn/longhorn-manager#deployment) on an ARM64 platform.
> 
> Let us know if you can successfully do it.

Will try to do a deploy and test it, thanks for your time.

**Comment by yasker** [comment]
Close this PR since it has been included in https://github.com/longhorn/longhorn-engine/pull/547 .

Thanks @ivang !

**Pull request closed without merging**
