### PR TITLE
update Longhorn engine base image and some dependencies

### PR DESCRIPTION
**Pull request by meldafrawi**
- Update Dockerfile.dapper base image to Ubuntu 20.04 and update dependencies
  - docker-cli to `20.10`
  - minio server to `2021-07-27T02-40-15Z`
  - grpcio & grpcio-tools to `v1.39.0`
  - protobuf to `3.17.3`
  - cattle to `0.5.4`
- Update Longhorn engine Dockerfile base image to Ubuntu 20.04
- bump `github.com/gorilla/websocket` version to `v1.4.2`

Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>

### CODE REVIEW

**Comment by meldafrawi** [comment]
This PR should be merged after https://github.com/longhorn/longhorn-engine/pull/631

**Comment by meldafrawi** [comment]
Ref: integration tests coretest results > https://ci.longhorn.io/job/private/job/longhorn-tests-regression/372/

**Comment by innobead** [comment]
> Ref: integration tests coretest results > https://ci.longhorn.io/job/private/job/longhorn-tests-regression/372/

Let's see the result before the merge.

**Comment by meldafrawi** [comment]
Some tests fail, in the PR check, but always pass with run them locally.

Log: 
```
ERRORS ====================================
____________________ ERROR at setup of test_replica_delete _____________________

request = <SubRequest 'grpc_controller_client' for <Function test_replica_delete>>
engine_manager_client = <rpc.instance_manager.process_manager_client.ProcessManagerClient object at 0xffffad07e340>

    @pytest.fixture
    def grpc_controller_client(request, engine_manager_client):
        e = create_engine_process(engine_manager_client)
        grpc_controller_client = ControllerClient(get_process_address(e))
>       get_controller_version_detail(grpc_controller_client)

core/conftest.py:39: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common/core.py:202: in get_controller_version_detail
    raise(grpc_err)
common/core.py:199: in get_controller_version_detail
    c = grpc_controller_client.version_detail_get()
rpc/controller/controller_client.py:82: in version_detail_get
    return self.stub.VersionDetailGet(empty_pb2.Empty())
.tox/py3/lib/python3.8/site-packages/grpc/_channel.py:946: in __call__
    return _end_unary_response_blocking(state, call, False, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

state = <grpc._channel._RPCState object at 0xffffad4a5430>
call = <grpc._cython.cygrpc.SegregatedCall object at 0xffffad085540>
with_call = False, deadline = None

    def _end_unary_response_blocking(state, call, with_call, deadline):
        if state.code is grpc.StatusCode.OK:
            if with_call:
                rendezvous = _MultiThreadedRendezvous(state, call, None, deadline)
                return state.response, rendezvous
            else:
                return state.response
        else:
>           raise _InactiveRpcError(state)
E           grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
E           	status = StatusCode.UNAVAILABLE
E           	details = "Broken pipe"
E           	debug_error_string = "{"created":"@1627911120.519770877","description":"Error received from peer ipv4:127.0.0.1:30001","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Broken pipe","grpc_status":14}"
E           >

.tox/py3/lib/python3.8/site-packages/grpc/_channel.py:849: _InactiveRpcError
___________________ ERROR at setup of test_remove_last_disk ____________________

process_manager_client = <rpc.instance_manager.process_manager_client.ProcessManagerClient object at 0xffffad4968e0>

    @pytest.fixture
    def grpc_replica_client(process_manager_client):
        r = create_replica_process(process_manager_client, REPLICA_NAME)
    
        listen = get_process_address(r)
        c = ReplicaClient(listen)
>       return cleanup_replica(c)

core/conftest.py:50: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common/core.py:183: in cleanup_replica
    r = get_replica(grpc_client)
common/core.py:169: in get_replica
    raise(grpc_err)
common/core.py:166: in get_replica
    r = grpc_client.replica_get()
rpc/replica/replica_client.py:23: in replica_get
    return self.stub.ReplicaGet(empty_pb2.Empty()).replica
.tox/py3/lib/python3.8/site-packages/grpc/_channel.py:946: in __call__
    return _end_unary_response_blocking(state, call, False, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

state = <grpc._channel._RPCState object at 0xffffad281730>
call = <grpc._cython.cygrpc.SegregatedCall object at 0xffffacf14500>
with_call = False, deadline = None

    def _end_unary_response_blocking(state, call, with_call, deadline):
        if state.code is grpc.StatusCode.OK:
            if with_call:
                rendezvous = _MultiThreadedRendezvous(state, call, None, deadline)
                return state.response, rendezvous
            else:
                return state.response
        else:
>           raise _InactiveRpcError(state)
E           grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
E           	status = StatusCode.UNAVAILABLE
E           	details = "Broken pipe"
E           	debug_error_string = "{"created":"@1627911159.557496815","description":"Error received from peer ipv4:127.0.0.1:10000","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Broken pipe","grpc_status":14}"
E           >

.tox/py3/lib/python3.8/site-packages/grpc/_channel.py:849: _InactiveRpcError
```

**Comment by meldafrawi** [comment]
After updating `instance-manager` version tag, there is only one error left in `test_replica_delete`


```
	==================================== ERRORS ====================================
2727s
24746	____________________ ERROR at setup of test_replica_delete _____________________
2727s
24747	
2727s
24748	request = <SubRequest 'grpc_controller_client' for <Function test_replica_delete>>
2727s
24749	engine_manager_client = <rpc.instance_manager.process_manager_client.ProcessManagerClient object at 0x7f6d87eba370>
2727s
24750	
2727s
24751	    @pytest.fixture
2727s
24752	    def grpc_controller_client(request, engine_manager_client):
2727s
24753	        e = create_engine_process(engine_manager_client)
2727s
24754	        grpc_controller_client = ControllerClient(get_process_address(e))
2727s
24755	>       get_controller_version_detail(grpc_controller_client)
2727s
24756	
2727s
24757	core/conftest.py:39: 
2727s
24758	_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2727s
24759	common/core.py:202: in get_controller_version_detail
2727s
24760	    raise(grpc_err)
2727s
24761	common/core.py:199: in get_controller_version_detail
2727s
24762	    c = grpc_controller_client.version_detail_get()
2727s
24763	rpc/controller/controller_client.py:82: in version_detail_get
2727s
24764	    return self.stub.VersionDetailGet(empty_pb2.Empty())
2727s
24765	.tox/py3/lib/python3.8/site-packages/grpc/_channel.py:946: in __call__
2727s
24766	    return _end_unary_response_blocking(state, call, False, None)
2727s
24767	_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2727s
24768	
2727s
24769	state = <grpc._channel._RPCState object at 0x7f6d87e816a0>
2727s
24770	call = <grpc._cython.cygrpc.SegregatedCall object at 0x7f6d87d393c0>
2727s
24771	with_call = False, deadline = None
2727s
24772	
2727s
24773	    def _end_unary_response_blocking(state, call, with_call, deadline):
2727s
24774	        if state.code is grpc.StatusCode.OK:
2727s
24775	            if with_call:
2727s
24776	                rendezvous = _MultiThreadedRendezvous(state, call, None, deadline)
2727s
24777	                return state.response, rendezvous
2727s
24778	            else:
2727s
24779	                return state.response
2727s
24780	        else:
2727s
24781	>           raise _InactiveRpcError(state)
2727s
24782	E           grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
2727s
24783	E           	status = StatusCode.UNAVAILABLE
2727s
24784	E           	details = "Broken pipe"
2727s
24785	E           	debug_error_string = "{"created":"@1627947115.172533269","description":"Error received from peer ipv4:127.0.0.1:30001","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Broken pipe","grpc_status":14}"
2727s
24786	E           >
2727s
24787	
2727s
24788	.tox/py3/lib/python3.8/site-packages/grpc/_channel.py:849: _InactiveRpcError
2727s
24789	
```

**Comment by innobead** [comment]
>  StatusCode.UNAVAILABLE

If you check other failed cases in the arm64 testbed, some other test cases were found and all caused by ` StatusCode.UNAVAILABLE`. It's more like a test stability issue instead of a specific test case.

**Comment by innobead** [comment]
This was caused by some uncertain compatibility between the latest version 1.39.*) of python gRPC client/tools with engine/instance manager gRPC implementation (based on 1.21.*).

For testing purposes, we can just use Python gRPC 1.25.* instead of the latest version, and it's Python 3 compatible. 

Closing this, and use #649 instead.

**Pull request closed without merging**
