### PR TITLE
vendor: update sparse-tools

### PR DESCRIPTION
**Pull request by ChanYiLin**
Issue: [longhorn/longhorn#4305](https://github.com/longhorn/longhorn/issues/4305)
Depends on: https://github.com/longhorn/sparse-tools/pull/93

### CODE REVIEW

**Review by innobead — DISMISSED** [review]

**Comment by innobead** [comment]
@ChanYiLin it seems the PR still having some conflicts, unable to merge. Please help update this again.

**Comment by ChanYiLin** [comment]
I think I have rebased with the master and updated the PR.
I can't find the conflict warning on this page.

**Comment by ChanYiLin** [comment]
@Mergifyio backport v1.4.x

**Comment by ChanYiLin** [comment]
@Mergifyio backport v1.4.x

**Comment by ChanYiLin** [comment]
@Mergifyio backport v1.4.x

**Comment by ChanYiLin** [comment]
@innobead I can't create backport in this repo
But these two work
- https://github.com/longhorn/backing-image-manager/pull/120
- https://github.com/longhorn/longhorn-instance-manager/pull/213

**Comment by innobead** [comment]
@ChanYiLin try to add another Mergifyio comment again, it should be able to trigger now. Try it.

**Comment by ChanYiLin** [comment]
@Mergifyio backport v1.4.x

**Comment by ChanYiLin** [comment]
@Mergifyio backport v1.4.x

**Comment by innobead** [comment]
I will check the permission later. It should work.

**Comment by ChanYiLin** [comment]
The true backport PR is here: https://github.com/longhorn/longhorn-engine/pull/888

**Pull request merged**
